# Generated by Django 4.2.3 on 2023-07-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
